config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :steps, only: [:show, :new, :create, :destroy] do
    resources :user_steps, only: :create
  end
  resources :user_steps, only: [:update, :destroy]
  # delete 'user_steps/:id' => 'user_steps#destroy', as: 'delete_user_step'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/step.rb
class Step < ApplicationRecord
  has_many :user_steps
  belongs_to :user, optional: true
  has_many_attached :files, dependent: :destroy

  validates :name, :content, presence: true
  validates :name, length: { minimum: 3 }
  validates :content, length: { minimum: 10 }

  scope :publicly_available, -> { where(user: nil) }
  scope :privately_available, -> { where.not(user: nil) }

  def url_files
    case name
    when "MDPH"
      return [{ name: "Demande à la MDPH",
                url: "https://res.cloudinary.com/daixhq5r5/image/upload/v1669947333/production/demande_%C3%A0_la_MDPH_f6pmsj.pdf",
                key: "demande_à_la_MDPH_f6pmsj" },
              { name: "Certificat médical",
                url: "https://res.cloudinary.com/daixhq5r5/image/upload/v1669947260/production/certificat_m%C3%A9dical_syzwo0.pdf",
                key: "certificat_médical_syzwo0" },
              { name: "Geva-sco",
                url: "https://res.cloudinary.com/daixhq5r5/image/upload/v1669947191/production/Geva-sco_sjyqul.pdf",
                key: "Geva-sco_sjyqul" }]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :user_steps
  has_many :steps, through: :user_steps
  has_many :private_steps, class_name: 'Step'

  validates :first_name, :last_name, presence: true
  validates :last_name, :first_name, length: { minimum: 3 }
end

app/models/user_step.rb
class UserStep < ApplicationRecord
  has_many_attached :files, dependent: :destroy
  belongs_to :user
  belongs_to :step
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_steps, :set_my_steps
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  private

  def set_steps
    @steps = Step.publicly_available
  end

  def set_my_steps
    @my_steps = Step.privately_available.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_action :set_user_steps, only: :show
  def show
  end

  def new
    @step = Step.new
  end

  def create
    @step = Step.new(step_params)
    @step.user = current_user
    if @step.save
      redirect_to step_path(@step)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @step.update(step_params)
    redirect_to step_path(@step)
  end

  def destroy
    @step.destroy
    redirect_to root_path, status: :see_other
  end

  def personal_step
    @steps = Step.where(personal: current_personal)
  end

  private

  def set_step
    @step = Step.find(params[:id])
  end

  def step_params
    params.require(:step).permit(:name, :content, files: [])
  end

  def set_user_steps
    @user_steps = UserStep.where(user: current_user, step: @step).order(created_at: :desc)
  end
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  before_action :set_user_step, only: %i[show edit update destroy]
  def new
    @step = Step.find(params[:step_id])
    @user_step = UserStep.new
  end

  def create
    @step = Step.find(params[:step_id])
    @user_step = UserStep.new
    @user_step.step = @step
    @user_step.user = current_user
    if @user_step.save
      redirect_to step_path(@step)
    else
      redirect_to step_path(@step), alert: "Ca n'a pas fonctionné: #{@user_step.errors.full_messages.join(', ')}"
    end
  end

  def edit
  end

  def update
    if @user_step.update(user_step_params)
      redirect_to step_path(@user_step.step)
    else
      redirect_to step_path(@user_step.step), alert: "Ca n'a pas fonctionné: #{@user_step.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @step = @user_step.step
    if @user_step.destroy
      redirect_to step_path(@step), status: :see_other
    else
      redirect_to step_path(@user_step.step)
    end
  end

  private

  def user_step_params
    params.require(:user_step).permit(:done, files: [])
  end

  def set_user_step
    @user_step = UserStep.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/composents/_footer.html.erb
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>À propos de nous</h6>
            <p class="text-justify">Hassist.me est une application crée dans le but d'aider les parents ayant un enfant atteint du trouble du spectre de l'autisme afin ne pas perdre de temps dans les démarches administratives.</p>
          </div>
          <div class="col-xs-2 col-md-3">
            <h6>LIENS RAPIDES</h6>
            <ul class="footer-links">
              <li><a href="mailto:nathanagn@gmail.com">Contactez-nous</a></li>
              <li><a href="#">Contribuez</a></li>
              <li><a href="#">Mentions légales</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">

          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
            <a href="mailto:nathanagn@gmail.com"><i class="fab fa-instagram"></i></a>
            <a href="mailto:nathanagn@gmail.com"><i class="fab fa-facebook"></i></a>
            <a href="mailto:nathanagn@gmail.com"><i class="fab fa-twitter"></i></a>
            <a href="mailto:nathanagn@gmail.com"><i class="fab fa-linkedin"></i></a>
            <a href="mailto:nathanagn@gmail.com"><i class="fa-sharp fa-solid fa-envelope"></i></a>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/composents/_list_of_steps.html.erb
<div class="list-group">
  <% steps.each do |step| %>
    <%= link_to step_path(step) do %>
      <div class="list-group-item list-group-item-action activecard text-center step-card-link bcc text-color2">
        <%= step.name %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="list-group" data-controller="reveal" data-reveal-hidden-class="d-none">
  <div class="list-group-item step-card-link list-group-item-action activecard text-center bcc color-text text-color1" data-action="click->reveal#toggle">
    Mes étapes
  </div>
    <%= link_to new_step_path do %>
      <div class="list-group-item list-group-item-action activecard text-center bcc step-card-link d-none color-text text-color1" data-reveal-target="item">
        Créer une étape
      </div>
    <% end %>
    <% @my_steps.each do |step| %>
      <%= link_to step_path(step) do %>
        <div class="list-group-item list-group-item-action activecard text-center step-card-link bcc d-none color-text text-color1" data-reveal-target="item">
          <%= step.name %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/composents/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/daixhq5r5/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1669140921/logo_mqxmwq.jpg" %>
    <% end %>

    <p class="notice d-none"><%= notice %></p>
    <p class="alert d-none"><%= alert %></p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <p class="lilita nav-link text-body fw-bold"><%= "#{current_user.last_name} #{current_user.first_name}" %></p>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" }, alt: "avatar" %>
            <% elsif current_user.photo.nil? == false %>
              <img src="<%= current_user.photo %>" alt="" class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"%>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/daixhq5r5/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1669141989/icons8-fl%C3%A8che-bas-30_2_w6yihb.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes étapes", "#", class: "dropdown-item" %>
              <%= link_to "Nouvelle étape", "#", class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/composents/_user_step_card.html.erb
<div class="card-user-step">
  <div class="d-flex justify-content-between">
    <p><%= l(user_step.created_at, format: "%e %b %Y", locale: 'en') %></p>
    <% if user_step.files.attached? %>
      <%= link_to user_step_path(user_step), data: { turbo_method: :delete, turbo_confirm: "Voulez vous vraiment supprimer ?" } do%>
        <i class="fa fa-trash-can text-secondary"></i>
      <%end %>
    <% end %>
  </div>
  <ul class="list-group list-group-flush">
    <% user_step.files.each do |file| %>
      <li class="list-group-item">
      <% if file.image? %>
      <div class="scrollable">
        <%= cl_image_tag file.key %>
      </div>
      <% else %>
        <iframe src=<%= "https://docs.google.com/gview?url=#{file.url}&embedded=true" %>></iframe>
      <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to file.url, target: "_blank", class: "text-secondary", download: file.blob.filename.to_s do %>
          <%= file.blob.filename.to_s %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% unless user_step.files.attached? %>
    <%= simple_form_for(user_step) do |f| %>
      <%= f.input :files, label: "Fichiers", as: :file, input_html: { multiple: true } %>
      <div class="d-flex justify-content-center">
        <%= f.submit 'Sauvegarder', class: "btn btn-gradient" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hassist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "https://res.cloudinary.com/daixhq5r5/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1669140921/logo_mqxmwq.jpg" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "composents/navbar" %>
    <% if user_signed_in? %>
      <div class="d-flex">
      <div class="list-width">
        <%= render "composents/list_of_steps", steps: @steps %>
      </div>
        <div class="p-4 flex-grow-1">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <% unless controller_name == 'sessions' %>
      <%= render 'composents/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgb(244 244 244 / 80%)), url(https://res.cloudinary.com/dikisdh8l/image/upload/v1669299620/Page_d_accueil_Hassist_gukj6k.jpg);">
    <div class="container">
      <h1 class ="text-center">Hassist</h1>
      <p data-controller="typed"></p>
      <% unless user_signed_in? %>
      <%= link_to "S'inscrire", new_user_registration_path, class: "btn btn-gradient mx-3" %>
      <%= link_to "Se connecter", new_user_session_path, class: "btn btn-gradient2 mx-3 " %>
      <% end %>
    </div>
  </div>

  <div class="description">
    <div class="container">
      <h2>Qu'est-ce que le Trouble du Spectre de l'Autisme (TSA) ?</h2>
        <p>Le trouble du spectre de l'autisme (TSA) est une condition neurodéveloppementale présente dès la naissance, dont les caractéristiques touchent plusieurs sphères du développement de l'enfant et peuvent changer dans le temps, aussi bien en nature qu'en intensité, et ce même à l'âge adulte. Les difficultés qui y sont reliées envahissent de nombreux domaines du fonctionnement de la personne.
          Le terme « spectre » fait référence au large éventail de manifestations, de compétences et de niveaux d’incapacité de fonctionnement qui peuvent survenir chez les personnes présentant un trouble du spectre de l’autisme (TSA). Certains enfants et adultes autistes sont pleinement capables d’effectuer toutes les activités de la vie quotidienne tandis que d’autres ont besoin d’un soutien substantiel pour effectuer les activités de base.

    </div>
  </div>
</div>

app/views/steps/new.html.erb
<div class="d-flex justify-content-center align-items-center mt-5">
  <div class="form-step-container">
    <h2 class="text-center">Créer une étape</h2>
    <%= simple_form_for(@step, html: { class: 'form-step' }) do |f| %>
      <%= f.input :name, label: "Nom de l'étape" %>
      <%= f.input :content, label: "Contenu"  %>
      <%= f.input :files, label: "Fichiers", as: :file, input_html: { multiple: true } %>
      <%= f.submit "Créer une étape", id: 'btt', class: "btn btn-success m-2 pulse" %>
    <% end %>
  </div>
</div>

app/views/steps/show.html.erb
<div class="step-cards">
  <div class="step-card-left p-3">
    <div class="bg-white p-3 rounded-4">
      <% if @step.user == current_user %>
      <div class="d-flex justify-content-end">
        <%= link_to step_path(@step), data: { turbo_method: :delete, turbo_confirm: "Voulez vous vraiment supprimer #{@step.name}?" } do %>
          <i class="fa fa-trash-can text-secondary"></i>
        <% end %>
      </div>
      <% end %>

      <% if @step.picture.nil? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/daixhq5r5/image/upload/v1669820915/enfants_uej7fr.png)">
         <h2><%= @step.name %></h2>
        </div>
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @step.picture %>)">
         <h2><%= @step.name %></h2>
        </div>
      <% end %>
      <p class="card-text p-3"><%= @step.content.html_safe %></p>
      <% if @step.files.attached? %>
        <ul class="list-group">
          <% @step.files.each do |file| %>
            <div class='card m-3'>
              <% if file.image? %>
                <div class="card-header scrollable">
                  <%= cl_image_tag file.key %>
                </div>
              <% else %>
                <div class='card-header'>
                  <iframe src=<%= "https://docs.google.com/gview?url=#{file.url}&embedded=true" %>></iframe>
                </div>
              <% end %>
              <div class='card-body'>
                <%= link_to file.url, target: "_blank", class: "text-secondary", download: file.blob.filename.to_s do %>
                  <%= file.blob.filename.to_s %>
                <% end %>
              </div>
            </div>
          <% end %>
        </ul>
      <% elsif @step.url_files.present? %>
      <ul class="list-group">
          <% @step.url_files.each do |file| %>
            <div class='card m-3'>
              <div class="card-header">
                <iframe src=<%= "https://docs.google.com/gview?url=#{file[:url]}&embedded=true" %>></iframe>
              </div>
              <div class='card-body'>
                <%= link_to cl_image_path(file[:key]), target: "_blank" do %>
                  <%= file[:name] %>
                <% end %>
              </div>
            </div>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="step-card-right user-steps-container rounded-4" data-controller="popover">
    <%= link_to step_user_steps_path(@step), title: "Créer une sauvegarde", data: { toggle: "tooltip", turbo_method: :post, turbo_confirm: "Vous êtes sur le point de créer une sauvegarde pour #{@step.name}. Continuer ?" }, class: 'link-card card-user-step d-flex justify-content-center align-items-center' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
    <template data-popover-target="content">
      <div data-popover-target="card" class ="card shadow rounded p-3 bg-light text-body">
        <p>Créer une sauvegarde</p>
      </div>
    </template>
    <% @user_steps.each do |user_step| %>
      <%= render 'composents/user_step_card', user_step: user_step %>
    <% end %>
  </div>
</div>

app/views/user_steps/new.html.erb
<%= simple_form_for (@step , @user_step) do |f| %>
  <%= f.input :file, label: "dossier" %>
  <%= f.submit %>
<% end %>

app/views/user_steps/show.html.erb
<div class="d-flex">
<div>
  <h2><%= @user_step.step.name %></h2>
</div>
<div class="list-width">
</div>
</div>